export const CARD_BG = [
  {
    id: 1,
    bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)",
  },
  {
    id: 2,
    bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdfa 100%)",
  },
  {
    id: 3,
    bgcolor: "linear-gradient(135deg, #ea7ff 0%, #f3fbff 100%)",
  },
  {
    id: 4,
    bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)",
  },
  {
    id: 5,
    bgcolor: "linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)",
  },
  {
    id: 6,
    bgcolor: "linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)",
  },
  {
    id: 7,
    bgcolor: "linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)",
  },
  {
    id: 8,
    bgcolor: "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)",
  },
  {
    id: 9,
    bgcolor: "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)",
  },
  {
    id: 10,
    bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)",
  },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your rolw, experience, and specific focus areas - all personalized to help you shine.",
  },
  {
    id: "02",
    title: "Learn at your Own Pace",
    description:
      "Expand answers only when you are ready, Dipe deeper into topics that matter most to you, and master the skills you need at your own pace.",
  },
  {
    id: "03",
    title: "Capture your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top - making it easy to track your progress and focus on what matters most.",
  },
  {
    id: "04",
    title: "Understand the 'WHY' Behind Answers",
    description:
      "Beyond just answers - unlock detailed concept explanations generated by AI to help you grasp the reasoning behind each response.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save and categorize your favorite questions and answers for quick access later, ensuring you can revisit key concepts whenever you need.",
  },
];
